name: CI

on:
   push:
     branches:
     - main
   pull_request:
     branches:
     - main
   release:
     types: [published]
   workflow_dispatch:

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install and run Mosquitto
      run: |
        brew install mosquitto
        mosquitto -d -c mosquitto/config/mosquitto.conf
    - name: SPM tests
      run: swift test --enable-code-coverage
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/mqtt-nioPackageTests.xctest/Contents/MacOs/mqtt-nioPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        file: info.lcov

  ios:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Xcodebuild
      run: |
        xcodebuild build -scheme mqtt-nio -destination 'platform=iOS Simulator,name=iPhone 11'

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: [5.3, 5.4, 5.5]
    services:
      mosquitto:
        image: adamfowlerphoto/mqttnio-mosquitto
        ports:
          - 1883:1883
          - 1884:1884
          - 8883:8883
          - 8080:8080
          - 8081:8081
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      env:
        MOSQUITTO_SERVER: mosquitto
      run: |
        swift test --enable-test-discovery --enable-code-coverage
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/mqtt-nioPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        file: info.lcov
